const fs = require('fs');
let inData = require('./data.json')

let Blocks = [
  {
    "name": "Feral Shudder",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 1,
    "action_type": "guard",
    "wildUse": 0,
    "value": 37
  },
  {
    "name": "Coiling Constriction",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 6,
    "action_type": "guard",
    "wildUse": 0,
    "value": 37
  },
  {
    "name": "Ink Field",
    "allowanceCost": 2,
    "guard_val": 40,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 9,
    "action_type": "guard",
    "wildUse": 0,
    "value": 36
  },
  {
    "name": "Frantic Retaliation",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 100,
    "counter_val": 30,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 10,
    "action_type": "guard",
    "wildUse": 0,
    "value": 38
  },
  {
    "name": "Instinctual Flail",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 16,
    "action_type": "guard",
    "wildUse": 0,
    "value": 37
  },
  {
    "name": "Tough Shell",
    "allowanceCost": 3,
    "guard_val": 40,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 21,
    "action_type": "guard",
    "wildUse": 0,
    "value": 52
  },
  {
    "name": "Prideful Stance",
    "allowanceCost": 2,
    "guard_val": 40,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 22,
    "action_type": "guard",
    "wildUse": 0,
    "value": 43
  },
  {
    "name": "Shell Brace",
    "allowanceCost": 3,
    "guard_val": 30,
    "success_level": 300,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 24,
    "action_type": "guard",
    "wildUse": 0,
    "value": 52
  },
  {
    "name": "Ignorant Thrash",
    "allowanceCost": 2,
    "guard_val": 40,
    "success_level": 90,
    "counter_val": 30,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 25,
    "action_type": "guard",
    "wildUse": 0,
    "value": 45
  },
  {
    "name": "Tuck In",
    "allowanceCost": 2,
    "guard_val": 40,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 30,
    "action_type": "guard",
    "wildUse": 0,
    "value": 36
  },
  {
    "name": "Unflinching Stance",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 200,
    "counter_val": 10,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 31,
    "action_type": "guard",
    "wildUse": 0,
    "value": 48
  },
  {
    "name": "Lasting Endurance",
    "allowanceCost": 3,
    "guard_val": 30,
    "success_level": 300,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 32,
    "action_type": "guard",
    "wildUse": 0,
    "value": 52
  },
  {
    "name": "Resist Stance",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 46,
    "action_type": "guard",
    "wildUse": 1,
    "value": 37
  },
  {
    "name": "Counter Stance",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 90,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 47,
    "action_type": "guard",
    "wildUse": 1,
    "value": 30
  },
  {
    "name": "Light Guard",
    "allowanceCost": 2,
    "guard_val": 10,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 48,
    "action_type": "guard",
    "wildUse": 1,
    "value": 32
  },
  {
    "name": "Shielding Aura",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 49,
    "action_type": "guard",
    "wildUse": 1,
    "value": 37
  },
  {
    "name": "Guardian Aura",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 90,
    "counter_val": 20,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 50,
    "action_type": "guard",
    "wildUse": 1,
    "value": 30
  },
  {
    "name": "Protecting Aura",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 51,
    "action_type": "guard",
    "wildUse": 1,
    "value": 30
  },
  {
    "name": "Counter Clash",
    "allowanceCost": 3,
    "guard_val": 30,
    "success_level": 90,
    "counter_val": 50,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 52,
    "action_type": "guard",
    "wildUse": 1,
    "value": 54
  },
  {
    "name": "Battle Hardened",
    "allowanceCost": 3,
    "guard_val": 60,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 53,
    "action_type": "guard",
    "wildUse": 1,
    "value": 54
  },
  {
    "name": "Reflective Radiance",
    "allowanceCost": 3,
    "guard_val": 40,
    "success_level": 90,
    "counter_val": 40,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 54,
    "action_type": "guard",
    "wildUse": 1,
    "value": 51
  },
  {
    "name": "Protecting Aura",
    "allowanceCost": 3,
    "guard_val": 60,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 55,
    "action_type": "guard",
    "wildUse": 1,
    "value": 54
  },
  {
    "name": "Heightened Senses",
    "allowanceCost": 2,
    "guard_val": 10,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "def",
    "speed": 3,
    "id": 56,
    "action_type": "guard",
    "wildUse": 1,
    "value": 32
  },
  {
    "name": "Defensive Stance",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 57,
    "action_type": "guard",
    "wildUse": 1,
    "value": 30
  }
]

let Attacks = [
  {
    "name": "Sudden Hop",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 80,
    "numHits": 1,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 0,
    "cal": "attack",
    "wildUse": 0,
    "value": 68
  },
  {
    "name": "Burrowing Strike",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 25,
    "speed": 4,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 2,
    "cal": "attack",
    "wildUse": 0,
    "value": 63
  },
  {
    "name": "Lurking Sting",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 25,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 3,
    "cal": "attack",
    "wildUse": 0,
    "value": 69
  },
  {
    "name": "Prideful Pursuit",
    "allowanceCost": 4,
    "damage_type": "atk",
    "damage_val": 35,
    "speed": 1,
    "faction": -1,
    "accuracy": 120,
    "numHits": 1,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 4,
    "cal": "attack",
    "wildUse": 0,
    "value": 94
  },
  {
    "name": "Frantic Bite",
    "allowanceCost": 4,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 2,
    "faction": -1,
    "accuracy": 110,
    "numHits": 2,
    "critical": 20,
    "recoil": 0,
    "targetType": 1,
    "id": 5,
    "cal": "attack",
    "wildUse": 0,
    "value": 87
  },
  {
    "name": "Sucker Slap",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 4,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 15,
    "recoil": 0,
    "targetType": 1,
    "id": 7,
    "cal": "attack",
    "wildUse": 0,
    "value": 68
  },
  {
    "name": "Rapid Fangs",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 15,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 2,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 8,
    "cal": "attack",
    "wildUse": 0,
    "value": 47
  },
  {
    "name": "Disturbing Buzz",
    "allowanceCost": 4,
    "damage_type": "spatk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 110,
    "numHits": 1,
    "critical": 70,
    "recoil": 0,
    "targetType": 1,
    "id": 11,
    "cal": "attack",
    "wildUse": 0,
    "value": 89
  },
  {
    "name": "Rapid Pecks",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 80,
    "numHits": 3,
    "critical": 40,
    "recoil": 0,
    "targetType": 1,
    "id": 12,
    "cal": "attack",
    "wildUse": 0,
    "value": 63
  },
  {
    "name": "Sliding Assault",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 4,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 10,
    "targetType": 1,
    "id": 13,
    "cal": "attack",
    "wildUse": 0,
    "value": 70
  },
  {
    "name": "Crooked Claws",
    "allowanceCost": 5,
    "damage_type": "atk",
    "damage_val": 60,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 14,
    "cal": "attack",
    "wildUse": 0,
    "value": 103
  },
  {
    "name": "Irritating Echoes",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 2,
    "id": 15,
    "cal": "attack",
    "wildUse": 0,
    "value": 68
  },
  {
    "name": "Scurrying Scratches",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 4,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 17,
    "cal": "attack",
    "wildUse": 0,
    "value": 69
  },
  {
    "name": "Sudden Snap",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 18,
    "cal": "attack",
    "wildUse": 0,
    "value": 58
  },
  {
    "name": "Preying Pounce",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 20,
    "recoil": 0,
    "targetType": 1,
    "id": 19,
    "cal": "attack",
    "wildUse": 0,
    "value": 65
  },
  {
    "name": "Harrowing Howls",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 3,
    "critical": 20,
    "recoil": 0,
    "targetType": 1,
    "id": 20,
    "cal": "attack",
    "wildUse": 0,
    "value": 65
  },
  {
    "name": "Reckless Rush",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 4,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 30,
    "targetType": 1,
    "id": 1,
    "cal": "attack",
    "wildUse": 0,
    "value": 70
  },
  {
    "name": "Dire Strike",
    "allowanceCost": 4,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 110,
    "numHits": 2,
    "critical": 80,
    "recoil": 0,
    "targetType": 1,
    "id": 26,
    "cal": "attack",
    "wildUse": 0,
    "value": 95
  },
  {
    "name": "Rapid Chatter",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 3,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 27,
    "cal": "attack",
    "wildUse": 0,
    "value": 69
  },
  {
    "name": "Head Charge",
    "allowanceCost": 5,
    "damage_type": "atk",
    "damage_val": 60,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 50,
    "recoil": 40,
    "targetType": 1,
    "id": 28,
    "cal": "attack",
    "wildUse": 0,
    "value": 122
  },
  {
    "name": "Delirous Fluttering",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 25,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 10,
    "targetType": 2,
    "id": 29,
    "cal": "attack",
    "wildUse": 0,
    "value": 68
  },
  {
    "name": "Spout Shot",
    "allowanceCost": 5,
    "damage_type": "spatk",
    "damage_val": 50,
    "speed": 1,
    "faction": -1,
    "accuracy": 110,
    "numHits": 1,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 33,
    "cal": "attack",
    "wildUse": 0,
    "value": 114
  },
  {
    "name": "Rolling Tackle",
    "allowanceCost": 4,
    "damage_type": "atk",
    "damage_val": 25,
    "speed": 1,
    "faction": -1,
    "accuracy": 70,
    "numHits": 3,
    "critical": 30,
    "recoil": 10,
    "targetType": 1,
    "id": 34,
    "cal": "attack",
    "wildUse": 0,
    "value": 83
  },
  {
    "name": "Tactical Takedown",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 30,
    "recoil": 10,
    "targetType": 1,
    "id": 35,
    "cal": "attack",
    "wildUse": 0,
    "value": 65
  },
  {
    "name": "Standard Strike",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 36,
    "cal": "attack",
    "wildUse": 1,
    "value": 46
  },
  {
    "name": "Brutal Blow",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 55,
    "speed": 1,
    "faction": -1,
    "accuracy": 80,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 37,
    "cal": "attack",
    "wildUse": 1,
    "value": 75
  },
  {
    "name": "Agile Attack",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 38,
    "cal": "attack",
    "wildUse": 1,
    "value": 39
  },
  {
    "name": "Rune Pulse",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 39,
    "cal": "attack",
    "wildUse": 1,
    "value": 51
  },
  {
    "name": "Malevolent Burst",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 55,
    "speed": 1,
    "faction": -1,
    "accuracy": 80,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 40,
    "cal": "attack",
    "wildUse": 1,
    "value": 75
  },
  {
    "name": "Fleeting Sparks",
    "allowanceCost": 2,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 41,
    "cal": "attack",
    "wildUse": 1,
    "value": 39
  },
  {
    "name": "Precision Strike",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 20,
    "recoil": 0,
    "targetType": 1,
    "id": 42,
    "cal": "attack",
    "wildUse": 1,
    "value": 65
  },
  {
    "name": "Beat Down",
    "allowanceCost": 4,
    "damage_type": "atk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 6,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 43,
    "cal": "attack",
    "wildUse": 1,
    "value": 92
  },
  {
    "name": "Spirit Rush",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 44,
    "cal": "attack",
    "wildUse": 1,
    "value": 58
  },
  {
    "name": "Elemental Surge",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 2,
    "id": 45,
    "cal": "attack",
    "wildUse": 1,
    "value": 68
  },
  {
    "name": "Light Attack",
    "allowanceCost": 1,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 58,
    "cal": "attack",
    "wildUse": 1,
    "value": 23
  },
  {
    "name": "Harmful Outcry",
    "allowanceCost": 1,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 59,
    "cal": "attack",
    "wildUse": 1,
    "value": 23
  }
]

let Statuses = [
  {
    "name": "Battle Stance",
    "allowanceCost": 2,
    "id": 60,
    "speed": 0,
    "t1": 0,
    "s1": "atk",
    "v1": 1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 33
  },
  {
    "name": "Combat Focus",
    "allowanceCost": 2,
    "id": 61,
    "speed": 0,
    "t1": 0,
    "s1": "spatk",
    "v1": 1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 33
  },
  {
    "name": "Up Tempo",
    "allowanceCost": 2,
    "id": 62,
    "speed": 1,
    "t1": 0,
    "s1": "spd",
    "v1": 1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 30
  },
  {
    "name": "Intimidate",
    "allowanceCost": 3,
    "id": 63,
    "speed": 1,
    "t1": 2,
    "s1": "atk",
    "v1": -1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 54
  },
  {
    "name": "Cower",
    "allowanceCost": 3,
    "id": 64,
    "speed": 1,
    "t1": 2,
    "s1": "spatk",
    "v1": -1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 54
  },
  {
    "name": "Glare",
    "allowanceCost": 3,
    "id": 65,
    "speed": 1,
    "t1": 2,
    "s1": "def",
    "v1": -1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 60
  },
  {
    "name": "Startle",
    "allowanceCost": 3,
    "id": 66,
    "speed": 1,
    "t1": 2,
    "s1": "spdef",
    "v1": -1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 60
  },
  {
    "name": "Gaze",
    "allowanceCost": 2,
    "id": 67,
    "speed": 1,
    "t1": 2,
    "s1": "spd",
    "v1": -1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 45
  },
  {
    "name": "Brace",
    "allowanceCost": 2,
    "id": 68,
    "speed": 2,
    "t1": 0,
    "s1": "def",
    "v1": 1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 48
  },
  {
    "name": "Sharp Mind",
    "allowanceCost": 2,
    "id": 69,
    "speed": 2,
    "t1": 0,
    "s1": "spdef",
    "v1": 1,
    "t2": 0,
    "s2": 0,
    "v2": 0,
    "t3": 0,
    "s3": 0,
    "v3": 0,
    "wildUse": 1,
    "value": 48
  }
 ]

for(ability of Attacks){
  let newAbility = {
      "critical" : ability.critical,
      "damage_type" : ability.damage_type,
      "damage_val" : ability.damage_val,
      "name" : ability.name,
      "speed" : ability.speed,
      "faction" : ability.faction,
      "action_type":"attack",
      "accuracy":ability.accuracy,
      "numHits":ability.numHits,
      "recoil":ability.recoil,
      "targetType":ability.targetType
  }
  newAbility = {
    "allowanceCost":ability.allowanceCost,
    "ability":newAbility,
    "id":ability.id,
    "wildUse":ability.wildUse
  }
  if(newAbility.id == "none"){
    newAbility.id = inData.baseAbilities.length
  }
  inData.baseAbilities[newAbility.id] = newAbility
}

for(ability of Blocks){
  let newAbility = {
      "action_type":"guard",
      "name":ability.name,
      "guard_val":ability.guard_val,
      "guard_type":ability.guard_type,
      "success_level":ability.success_level,
      "counter_val":ability.counter_val,
      "counter_type":ability.counter_type,
      "speed":ability.speed
  }
  newAbility = {
    "allowanceCost":ability.allowanceCost,
    "ability":newAbility,
    "id":ability.id,
    "wildUse":ability.wildUse
  }
  if(newAbility.id == "none"){
    newAbility.id = inData.baseAbilities.length
  }
  inData.baseAbilities[newAbility.id] = newAbility
}

for(ability of Statuses){
  let newAbility = {
    "action_type": "stats",
    "name": ability.name,
    "statChangeCount": 1,
    "effects": [],
    "speed": ability.speed
  }
  for(var i = 3; i > 0; i--){
    if(ability["v" + i] != 0){
      newAbility.effects[(i - 1)] = {
        "target": "" + ability["t" + i],
        "stat": ability["s" + i],
        "value": ability["v" + i]
      }
    }
  }
  newAbility.statChangeCount = newAbility.effects.length
  newAbility = {
    "allowanceCost":ability.allowanceCost,
    "ability":newAbility,
    "id":ability.id,
    "wildUse":ability.wildUse
  }
  if(newAbility.id == "none"){
    newAbility.id = inData.baseAbilities.length
  }
  inData.baseAbilities[newAbility.id] = newAbility
}



let data = JSON.stringify(inData,null,2);
fs.writeFileSync('data.json', data);