const fs = require('fs');
let inData = require('./data.json')

let Blocks = [
  {
    "name": "Protecting Aura",
    "allowanceCost": 4,
    "guard_val": 60,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 55,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Reflective Radiance",
    "allowanceCost": 4,
    "guard_val": 40,
    "success_level": 90,
    "counter_val": 40,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 54,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Battle Hardened",
    "allowanceCost": 4,
    "guard_val": 60,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 53,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Counter Clash",
    "allowanceCost": 4,
    "guard_val": 30,
    "success_level": 90,
    "counter_val": 50,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 52,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Protecting Aura",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 51,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Guardian Aura",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 90,
    "counter_val": 20,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 50,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Shielding Aura",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 49,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Defensive Stance",
    "allowanceCost": 2,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 57,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Heightened Senses",
    "allowanceCost": 1,
    "guard_val": 10,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 56,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Light Guard",
    "allowanceCost": 1,
    "guard_val": 10,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 48,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Counter Stance",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 90,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 47,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Resist Stance",
    "allowanceCost": 2,
    "guard_val": 20,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 46,
    "action_type": "guard",
    "wildUse": 1
  },
  {
    "name": "Lasting Endurance",
    "allowanceCost": 4,
    "guard_val": 30,
    "success_level": 300,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 32,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Unflinching Stance",
    "allowanceCost": 4,
    "guard_val": 30,
    "success_level": 200,
    "counter_val": 10,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 31,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Tuck In",
    "allowanceCost": 3,
    "guard_val": 40,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 30,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Ignorant Thrash",
    "allowanceCost": 4,
    "guard_val": 40,
    "success_level": 90,
    "counter_val": 30,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 25,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Shell Brace",
    "allowanceCost": 4,
    "guard_val": 30,
    "success_level": 300,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 24,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Prideful Stance",
    "allowanceCost": 4,
    "guard_val": 40,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 22,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Tough Shell",
    "allowanceCost": 4,
    "guard_val": 40,
    "success_level": 200,
    "counter_val": 0,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 21,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Instinctual Flail",
    "allowanceCost": 3,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 16,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Frantic Retaliation",
    "allowanceCost": 3,
    "guard_val": 20,
    "success_level": 100,
    "counter_val": 30,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 10,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Ink Field",
    "allowanceCost": 3,
    "guard_val": 40,
    "success_level": 100,
    "counter_val": 0,
    "counter_type": "spdef",
    "guard_type": "spdef",
    "speed": 3,
    "id": 9,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Coiling Constriction",
    "allowanceCost": 3,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 6,
    "action_type": "guard",
    "wildUse": 0
  },
  {
    "name": "Feral Shudder",
    "allowanceCost": 3,
    "guard_val": 30,
    "success_level": 100,
    "counter_val": 20,
    "counter_type": "def",
    "guard_type": "def",
    "speed": 3,
    "id": 1,
    "action_type": "guard",
    "wildUse": 0
  }
]
let Attacks = [
  {
    "name": "Sudden Hop",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 2,
    "faction": -1,
    "accuracy": 80,
    "numHits": 1,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 0,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Burrowing Strike",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 4,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 2,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Lurking Sting",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 3,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Prideful Pursuit",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 1,
    "faction": -1,
    "accuracy": 120,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 4,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Frantic Bite",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 2,
    "faction": -1,
    "accuracy": 110,
    "numHits": 1,
    "critical": 40,
    "recoil": 0,
    "targetType": 1,
    "id": 5,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Sucker Slap",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 4,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 30,
    "recoil": 0,
    "targetType": 1,
    "id": 7,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Rapid Fangs",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 2,
    "critical": 20,
    "recoil": 0,
    "targetType": 1,
    "id": 8,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Disturbing Buzz",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 30,
    "speed": 1,
    "faction": -1,
    "accuracy": 110,
    "numHits": 1,
    "critical": 30,
    "recoil": 0,
    "targetType": 1,
    "id": 11,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Rapid Pecks",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 3,
    "critical": 40,
    "recoil": 0,
    "targetType": 1,
    "id": 12,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Sliding Assault",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 4,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 10,
    "targetType": 1,
    "id": 13,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Crooked Claws",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 60,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 14,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Irritating Echoes",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 30,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 2,
    "id": 15,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Scurrying Scratches",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 4,
    "critical": 30,
    "recoil": 0,
    "targetType": 1,
    "id": 17,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Sudden Snap",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 18,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Preying Pounce",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 40,
    "recoil": 0,
    "targetType": 1,
    "id": 19,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Harrowing Howls",
    "allowanceCost": 2,
    "damage_type": "spatk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 3,
    "critical": 50,
    "recoil": 0,
    "targetType": 1,
    "id": 20,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Reckless Rush",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 4,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 30,
    "targetType": 1,
    "id": 23,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Dire Strike",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 110,
    "numHits": 1,
    "critical": 80,
    "recoil": 0,
    "targetType": 1,
    "id": 26,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Rapid Chatter",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 3,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 27,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Head Charge",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 60,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 50,
    "recoil": 40,
    "targetType": 1,
    "id": 28,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Delirous Fluttering",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 30,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 10,
    "targetType": 2,
    "id": 29,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Spout Shot",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 50,
    "speed": 1,
    "faction": -1,
    "accuracy": 110,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 33,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Rolling Tackle",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 30,
    "speed": 1,
    "faction": -1,
    "accuracy": 70,
    "numHits": 3,
    "critical": 30,
    "recoil": 10,
    "targetType": 1,
    "id": 34,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Tactical Takedown",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 50,
    "recoil": 10,
    "targetType": 1,
    "id": 35,
    "cal": "attack",
    "wildUse": 0
  },
  {
    "name": "Standard Strike",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 36,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Brutal Blow",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 60,
    "speed": 1,
    "faction": -1,
    "accuracy": 80,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 37,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Agile Attack",
    "allowanceCost": 2,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 38,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Rune Pulse",
    "allowanceCost": 2,
    "damage_type": "spatk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 39,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Malevolent Burst",
    "allowanceCost": 2,
    "damage_type": "spatk",
    "damage_val": 60,
    "speed": 1,
    "faction": -1,
    "accuracy": 80,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 40,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Fleeting Sparks",
    "allowanceCost": 2,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 41,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Precision Strike",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 40,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 40,
    "recoil": 0,
    "targetType": 1,
    "id": 42,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Light Attack",
    "allowanceCost": 1,
    "damage_type": "atk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 58,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Harmful Outcry",
    "allowanceCost": 1,
    "damage_type": "spatk",
    "damage_val": 20,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 59,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Beat Down",
    "allowanceCost": 3,
    "damage_type": "atk",
    "damage_val": 10,
    "speed": 1,
    "faction": -1,
    "accuracy": 90,
    "numHits": 6,
    "critical": 0,
    "recoil": 0,
    "targetType": 1,
    "id": 43,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Spirit Rush",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 40,
    "speed": 2,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 10,
    "recoil": 0,
    "targetType": 1,
    "id": 44,
    "cal": "attack",
    "wildUse": 1
  },
  {
    "name": "Elemental Surge",
    "allowanceCost": 3,
    "damage_type": "spatk",
    "damage_val": 30,
    "speed": 1,
    "faction": -1,
    "accuracy": 100,
    "numHits": 1,
    "critical": 0,
    "recoil": 0,
    "targetType": 2,
    "id": 45,
    "cal": "attack",
    "wildUse": 1
  }
]


for(ability of Attacks){
  let newAbility = {
      "critical" : ability.critical,
      "damage_type" : ability.damage_type,
      "damage_val" : ability.damage_val,
      "name" : ability.name,
      "speed" : ability.speed,
      "faction" : ability.faction,
      "action_type":"attack",
      "accuracy":ability.accuracy,
      "numHits":ability.numHits,
      "recoil":ability.recoil,
      "targetType":ability.targetType
  }
  newAbility = {
    "allowanceCost":ability.allowanceCost,
    "ability":newAbility,
    "id":ability.id,
    "wildUse":ability.wildUse
  }
  if(newAbility.id == "none"){
    newAbility.id = inData.baseAbilities.length
  }
  inData.baseAbilities[newAbility.id] = newAbility
}

for(ability of Blocks){
  newAbility = {
      "action_type":"guard",
      "name":ability.name,
      "guard_val":ability.guard_val,
      "guard_type":ability.guard_type,
      "success_level":ability.success_level,
      "counter_val":ability.counter_val,
      "counter_type":ability.counter_type,
      "speed":ability.speed
  }
  newAbility = {
    "allowanceCost":ability.allowanceCost,
    "ability":newAbility,
    "id":ability.id,
    "wildUse":ability.wildUse
  }
  if(newAbility.id == "none"){
    newAbility.id = inData.baseAbilities.length
  }
  inData.baseAbilities[newAbility.id] = newAbility
}



let data = JSON.stringify(inData,null,2);
fs.writeFileSync('data.json', data);